- hosts: localhost
  vars:
    name: ansbile
  pre_tasks:
    - file:
        path:  roles
        state: absent
    - local_action:
        command ansible-galaxy install -r requirements.yml --roles-path roles/git
  roles:
    - docker
    - delivering-files 
  